version: '3'

services:
  jupyter-notebook:
    build: ./jupyter/
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=  
    volumes:
      - ./data:/home/jovyan/data
      - ./jupyter/notebooks:/home/jovyan/notebook

    
