version: 1

services:
  jupyter-notebooks:
      networks:
        - playground
      build: ./jupyter/
      ports:
        - "8888:8888"
      volumes:
        - ./data: ./data
        - ./jupyter/notebooks: ./jupyter/notebooks
      container_name: jupyter-notebooks